# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95bff3104848ee18ed00ae2985439cfa2fce0b94d61740ba067439037120cf5482764c669ff0089e843c259c1401e19630cb73003d3fc188bde6c981231dee9

test:
  secret_key_base: 8196c73d7b5bff9caacf6b3e5b0e177165ca3e1b201e916bbfc3a01f56c1f81bb35d05de80f44e63ccb6995b0a5bd3374c0ece555f2c1c908de44eea59dc6a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
